<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Articulo;

class ArticuloSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $articles = [
            [
                'clave'            => '713770009',
                'clave_alterna'    => '713770009',
                'es_servicio'      => 0,
                'descripcion'      => 'ADORNO DE PARED  NUBE',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 145.00,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],
            [
                'clave'            => '485180006',
                'clave_alterna'    => '485180006',
                'es_servicio'      => 0,
                'descripcion'      => 'ADORNO DE PARED  TARIK',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 234.09,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],
            [
                'clave'            => '000714270003',
                'clave_alterna'    => '000714270003',
                'es_servicio'      => 0,
                'descripcion'      => 'ADORNO DE PARED CRUZ',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 162.00,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],[
                'clave'            => '000775180006',
                'clave_alterna'    => '000775180006',
                'es_servicio'      => 0,
                'descripcion'      => 'ADORNO DE PARED ESTRELLA LYRA',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 178.00,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],[
                'clave'            => '42637',
                'clave_alterna'    => '42637',
                'es_servicio'      => 0,
                'descripcion'      => 'ADORNO NAVIDEÑO CHRISTMAS TREE',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 64.00,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],[
                'clave'            => '000882520009',
                'clave_alterna'    => '000882520009',
                'es_servicio'      => 0,
                'descripcion'      => 'ALMOHADA ABRAZABLE HARRY POTTER',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 243.00,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],[
                'clave'            => '000356460008',
                'clave_alterna'    => '000356460008',
                'es_servicio'      => 0,
                'descripcion'      => 'ALMOHADA BABY VIALIFRESH',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 419.00,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],[
                'clave'            => '107308661',
                'clave_alterna'    => '107308661',
                'es_servicio'      => 0,
                'descripcion'      => 'ALMOHADA BODY PILLOW CHOCOLATE',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 237.00,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],[
                'clave'            => '000352090001',
                'clave_alterna'    => '000352090001',
                'es_servicio'      => 0,
                'descripcion'      => 'ALMOHADA STD VIALIFRESH SUPER CONFORT',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 202.00,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],[
                'clave'            => '7501278444730',
                'clave_alterna'    => '7501278444730',
                'es_servicio'      => 0,
                'descripcion'      => 'ALMOHADA PILLOW BODY SIESTA VINO',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 247.20,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],[
                'clave'            => '6901',
                'clave_alterna'    => '6901',
                'es_servicio'      => 0,
                'descripcion'      => 'BATITA DE BAÑO CUPCAKE CHIQUI',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 165.00,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],[
                'clave'            => '9878',
                'clave_alterna'    => '9878',
                'es_servicio'      => 0,
                'descripcion'      => 'CAMINADOR ALAS MAGICAS',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 140.00,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],[
                'clave'            => '000499960007',
                'clave_alterna'    => '000499960007',
                'es_servicio'      => 0,
                'descripcion'      => 'VAJILLA AZUL BIASI',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 259.00,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],[
                'clave'            => '000924050006',
                'clave_alterna'    => '000924050006',
                'es_servicio'      => 0,
                'descripcion'      => 'VINIL DECORATIVO  UNICORNIO',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 128.79,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],[
                'clave'            => '000867270004',
                'clave_alterna'    => '000867270004',
                'es_servicio'      => 0,
                'descripcion'      => 'VIANNEY HOME VELAS 250 GR BERRY MANDARIN',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 162.00,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ],[
                'clave'            => '000876150007',
                'clave_alterna'    => '000876150007',
                'es_servicio'      => 0,
                'descripcion'      => 'ALMOHADA ABRAZABLE DINOSAURIOS',
                'id_categoria'     => 1,
                'id_unidad_compra' => 2,
                'id_unidad_venta'  => 2,
                'factor'           => 1,
                'id_impuesto'      => null,
                'precio_compra'    => 419.00,
                'es_precio_neto'   => 0,
                'id_precio'        => 2,
                'id_moneda'        => 1,
                'tasa_cambio'      => 1,
                'clave_sat'        => 'NA',
                'inventario_min'   => 1,
                'inventario_max'   => 10,
                'localizacion'     => 'Pasillo 2',
                'imagenes'         => '[]',
                'caracteristicas'  => '',
                'etiquetas'        => '[]',
                'activo'           => 1,
                'eliminado'        => 0,
            ]
        ];
        foreach ($articles as $item) {
            Articulo::create($item);
        }
    }
}
